# Generated by Django 5.2.4 on 2026-07-30 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CensusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateField(blank=True, help_text='The date this census data represents (e.g., end of quarter).', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='The active snapshot used for the org chart. Only one per company.')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='census_uploads/')),
                ('employee_count', models.IntegerField(default=0)),
                ('warnings_count', models.IntegerField(default=0)),
                ('column_mapping', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('active', 'Active'), ('archived', 'Archived')], default='processing', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='org_view.company')),
            ],
            options={
                'ordering': ['-effective_date', '-upload_date'],
                'get_latest_by': 'effective_date',
            },
        ),
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('branch_root_employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_view_permissions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='org_view.company')),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('raw_supervisor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('management_level', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('site_location', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('employee_status', models.CharField(blank=True, max_length=50)),
                ('employee_type', models.CharField(blank=True, max_length=50)),
                ('pay_type', models.CharField(blank=True, max_length=50)),
                ('annual_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fully_loaded_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_overhead', models.BooleanField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('revenue_attribution', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('entity', models.CharField(blank=True, max_length=200)),
                ('union_affiliation', models.CharField(blank=True, max_length=200)),
                ('flsa_status', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='org_view.censussnapshot')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='org_view.employee')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['snapshot'], name='org_view_em_snapsho_8cbfa8_idx'), models.Index(fields=['raw_supervisor_id'], name='org_view_em_raw_sup_3caea5_idx'), models.Index(fields=['supervisor'], name='org_view_em_supervi_26e284_idx'), models.Index(fields=['management_level'], name='org_view_em_managem_c5f373_idx'), models.Index(fields=['entity'], name='org_view_em_entity_8d9ba5_idx')],
                'unique_together': {('snapshot', 'employee_id')},
            },
        ),
    ]
