# Generated by Django 5.2.4 on 2026-07-30 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_view', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermission',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (edit + pay)'), ('viewer', 'Viewer (read + pay)'), ('restricted', 'Restricted (read, no pay)')], default='viewer', max_length=20),
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_snapshot', models.ForeignKey(blank=True, help_text='The snapshot this scenario was cloned from (its baseline for comparison).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='org_view.censussnapshot')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='org_view.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('source_employee_id', models.CharField(blank=True, default='', max_length=50)),
                ('change_type', models.CharField(choices=[('unchanged', 'Unchanged'), ('modified', 'Modified'), ('moved', 'Moved'), ('added', 'Added'), ('removed', 'Eliminated')], default='unchanged', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('raw_supervisor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('management_level', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('site_location', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('employee_status', models.CharField(blank=True, max_length=50)),
                ('employee_type', models.CharField(blank=True, max_length=50)),
                ('pay_type', models.CharField(blank=True, max_length=50)),
                ('annual_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fully_loaded_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_overhead', models.BooleanField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('revenue_attribution', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('entity', models.CharField(blank=True, max_length=200)),
                ('union_affiliation', models.CharField(blank=True, max_length=200)),
                ('flsa_status', models.CharField(blank=True, max_length=50)),
                ('is_vacant', models.BooleanField(default=False, help_text='Planned / to-be-hired role with no incumbent.')),
                ('note', models.TextField(blank=True, help_text='Rationale for this change (shown in the change log).')),
                ('baseline_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='org_view.scenario')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['scenario'], name='org_view_sc_scenari_262209_idx'), models.Index(fields=['scenario', 'change_type'], name='org_view_sc_scenari_cb11f8_idx')],
                'unique_together': {('scenario', 'employee_id')},
            },
        ),
    ]
