# Generated by Django 5.2.4 on 2026-07-31 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_view', '0002_scenarios_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioposition',
            name='prior_supervisor_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='CorrectionReplayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('applied_count', models.IntegerField(default=0)),
                ('drifted_count', models.IntegerField(default=0)),
                ('stale_count', models.IntegerField(default=0)),
                ('conflict_count', models.IntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_logs', to='org_view.company')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_logs', to='org_view.censussnapshot')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='StructureCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=50)),
                ('kind', models.CharField(choices=[('reparent', 'Change manager'), ('set_root', 'Make top of org'), ('attribute', 'Correct attributes'), ('exclude', 'Exclude from chart')], max_length=20)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, help_text='Why this correction was made.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive corrections are kept for audit but no longer replayed.')),
                ('replay_status', models.CharField(choices=[('applied', 'Applied'), ('drifted', 'Applied — source value changed'), ('stale', 'Person not in current census'), ('conflict', 'Could not apply')], default='applied', max_length=20)),
                ('replay_detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='org_view.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('first_applied_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_first_applied', to='org_view.censussnapshot')),
                ('last_applied_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_last_applied', to='org_view.censussnapshot')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='org_view_st_company_1ef405_idx'), models.Index(fields=['company', 'replay_status'], name='org_view_st_company_00fc8a_idx')],
                'unique_together': {('company', 'employee_id', 'kind')},
            },
        ),
    ]
