# Generated by Django 5.2.4 on 2026-07-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_view', '0003_corrections_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionreplaylog',
            name='resolved_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='structurecorrection',
            name='kind',
            field=models.CharField(choices=[('reparent', 'Change manager'), ('set_root', 'Make top of org'), ('attribute', 'Correct attributes'), ('exclude', 'Exclude from chart'), ('add_person', 'Add missing person')], max_length=20),
        ),
        migrations.AlterField(
            model_name='structurecorrection',
            name='replay_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('drifted', 'Applied — source value changed'), ('stale', 'Person not in current census'), ('conflict', 'Could not apply'), ('resolved', 'Source now includes this person')], default='applied', max_length=20),
        ),
    ]
