# Generated by Django 5.2.4 on 2026-07-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_view', '0004_add_person_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurecorrection',
            name='kind',
            field=models.CharField(choices=[('reparent', 'Change manager'), ('set_root', 'Make top of org'), ('attribute', 'Correct attributes'), ('exclude', 'Exclude from chart'), ('add_person', 'Add missing person'), ('eliminate', 'Eliminate position')], max_length=20),
        ),
    ]
