# Generated by Django 5.2.4 on 2026-07-31 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_view', '0005_eliminate_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_employee_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('member_ids', models.JSONField(blank=True, default=list)),
                ('accent', models.CharField(choices=[('sand', 'Sand'), ('sage', 'Sage'), ('slate', 'Slate'), ('plum', 'Plum')], default='sand', max_length=20)),
                ('collapsed_by_default', models.BooleanField(default=True, help_text='Decluttering only helps if the box starts closed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_groups', to='org_view.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parent_employee_id', 'name'],
                'indexes': [models.Index(fields=['company', 'parent_employee_id'], name='org_view_ch_company_43dc68_idx')],
                'unique_together': {('company', 'parent_employee_id', 'name')},
            },
        ),
    ]
