# Generated by Django 5.2.4 on 2026-07-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_view', '0006_chart_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='chartgroup',
            unique_together={('company', 'name')},
        ),
        migrations.AlterField(
            model_name='chartgroup',
            name='parent_employee_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
